/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.buscarMaterial;

import controlador.ControladorVistaListaMaterial;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import vista.Herramientas.vistaAltaHerramientaNoConsumible;
import controlador.BajaControlador;
import controlador.ModificarConsumibleControlador;
import controlador.ModificarNoConsumibleControlador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import vista.Herramientas.vistaAltaHerramientaConsumible;
import vista.Herramientas.vistaModificarConsumible;
import vista.Herramientas.vistaModificarNoConsumible;

/**
 *
 * @author Mr.Robot
 */
public class VistaListaMaterial extends javax.swing.JFrame {
    DefaultTableModel modeloTabla = null;    
    private ControladorVistaListaMaterial controlador = null;
    
    //vistaModificarConsumible vistaModi = new vistaModificarConsumible();
    //vistaModificarNoConsumible vistaModiNo = new vistaModificarNoConsumible();
    
    /**
     * Creates new form VistaListaMaterial
     */
    public VistaListaMaterial() {
        
        initComponents();
        
        modeloTabla = new DefaultTableModel();
                
        modeloTabla.addColumn("ID UTNG");
        modeloTabla.addColumn("ID Estatal");
        modeloTabla.addColumn("Descripción");
        modeloTabla.addColumn("No. activo");
        modeloTabla.addColumn("No. serie");
        modeloTabla.addColumn("Marca");
        modeloTabla.addColumn("Modelo");
        modeloTabla.addColumn("Costo");
        modeloTabla.addColumn("Estado");
        modeloTabla.addColumn("Disposición");
        modeloTabla.addColumn("Tipo");
        
        tblMaterial.setModel(modeloTabla);
        controlador = new ControladorVistaListaMaterial(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipMat = new javax.swing.ButtonGroup();
        tipId = new javax.swing.ButtonGroup();
        jPFondo = new javax.swing.JPanel();
        jPDatos = new util.fondo.TransparentPanel();
        jPTablaMaterial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        btnAgregarNoConsumible = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregarConsumible = new javax.swing.JButton();
        btnImprimirHerramientas1 = new javax.swing.JButton();
        lblNoControl = new javax.swing.JLabel();
        txtNoControl = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jRBConsumible = new javax.swing.JRadioButton();
        jRBNoConsumible = new javax.swing.JRadioButton();
        jRBLocal = new javax.swing.JRadioButton();
        jRBEstatal = new javax.swing.JRadioButton();
        jRBUTNG = new javax.swing.JRadioButton();
        btnVolver = new javax.swing.JButton();
        jRBCveMatCon = new javax.swing.JRadioButton();
        jMBar = new javax.swing.JMenuBar();
        jMOpciones = new javax.swing.JMenu();
        jMICerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Material");
        setResizable(false);

        jPTablaMaterial.setOpaque(false);

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMaterial);

        btnAgregarNoConsumible.setBackground(new java.awt.Color(40, 167, 69));
        btnAgregarNoConsumible.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnAgregarNoConsumible.setText("AGREGAR NO CONSUMIBLE");
        btnAgregarNoConsumible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNoConsumibleActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(40, 167, 69));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(40, 167, 69));
        btnModificar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAgregarConsumible.setBackground(new java.awt.Color(40, 167, 69));
        btnAgregarConsumible.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnAgregarConsumible.setText("AGREGAR CONSUMIBLE");
        btnAgregarConsumible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarConsumibleActionPerformed(evt);
            }
        });

        btnImprimirHerramientas1.setBackground(new java.awt.Color(0, 0, 102));
        btnImprimirHerramientas1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnImprimirHerramientas1.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirHerramientas1.setText("IMPRIMIR HERRAMIENTAS");
        btnImprimirHerramientas1.setBorder(null);
        btnImprimirHerramientas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirHerramientas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTablaMaterialLayout = new javax.swing.GroupLayout(jPTablaMaterial);
        jPTablaMaterial.setLayout(jPTablaMaterialLayout);
        jPTablaMaterialLayout.setHorizontalGroup(
            jPTablaMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTablaMaterialLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPTablaMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarNoConsumible)
                    .addComponent(btnAgregarConsumible))
                .addGap(96, 96, 96)
                .addGroup(jPTablaMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTablaMaterialLayout.createSequentialGroup()
                        .addComponent(btnImprimirHerramientas1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPTablaMaterialLayout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(btnModificar)
                        .addGap(103, 103, 103))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTablaMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPTablaMaterialLayout.setVerticalGroup(
            jPTablaMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTablaMaterialLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPTablaMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarNoConsumible)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar))
                .addGap(18, 18, 18)
                .addGroup(jPTablaMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarConsumible)
                    .addComponent(btnImprimirHerramientas1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        lblNoControl.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblNoControl.setText("Buscar:");

        txtNoControl.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(40, 167, 69));
        btnBuscar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tipMat.add(jRBConsumible);
        jRBConsumible.setText("Consumible");

        tipMat.add(jRBNoConsumible);
        jRBNoConsumible.setText("No Consumible");

        tipId.add(jRBLocal);
        jRBLocal.setText("ID Local");

        tipId.add(jRBEstatal);
        jRBEstatal.setText("ID Estatal ");

        tipId.add(jRBUTNG);
        jRBUTNG.setText("ID UTNG");

        btnVolver.setBackground(java.awt.Color.gray);
        btnVolver.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnVolver.setText("Volver");

        tipId.add(jRBCveMatCon);
        jRBCveMatCon.setText("cveMatCon");

        javax.swing.GroupLayout jPDatosLayout = new javax.swing.GroupLayout(jPDatos);
        jPDatos.setLayout(jPDatosLayout);
        jPDatosLayout.setHorizontalGroup(
            jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPDatosLayout.createSequentialGroup()
                        .addComponent(lblNoControl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNoControl))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPDatosLayout.createSequentialGroup()
                        .addComponent(jRBConsumible)
                        .addGap(18, 18, 18)
                        .addComponent(jRBNoConsumible)
                        .addGap(248, 248, 248)
                        .addComponent(jRBCveMatCon)
                        .addGap(18, 18, 18)
                        .addComponent(jRBLocal)))
                .addGap(18, 18, 18)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosLayout.createSequentialGroup()
                        .addComponent(jRBUTNG)
                        .addGap(18, 18, 18)
                        .addComponent(jRBEstatal))
                    .addGroup(jPDatosLayout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPTablaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPDatosLayout.setVerticalGroup(
            jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoControl)
                    .addComponent(txtNoControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnVolver))
                .addGap(27, 27, 27)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBConsumible)
                    .addComponent(jRBNoConsumible)
                    .addComponent(jRBLocal)
                    .addComponent(jRBEstatal)
                    .addComponent(jRBUTNG)
                    .addComponent(jRBCveMatCon))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPTablaMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jMBar.setOpaque(true);

        jMOpciones.setText("Opciones");

        jMICerrarSesion.setText("Cerrar Sesión");
        jMOpciones.add(jMICerrarSesion);

        jMBar.add(jMOpciones);

        setJMenuBar(jMBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarNoConsumibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNoConsumibleActionPerformed
        // TODO add your handling code here:
        vistaAltaHerramientaNoConsumible altaNoConsumible = new vistaAltaHerramientaNoConsumible();
        
        altaNoConsumible.setVisible(true);
    }//GEN-LAST:event_btnAgregarNoConsumibleActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        BajaControlador baja;
        try {
            baja = new BajaControlador(this);
            baja.eliminarMaterial();
        } catch (SQLException ex) {
            Logger.getLogger(VistaListaMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //baja.eliminarMaterial();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        vistaModificarConsumible vistaModi = new vistaModificarConsumible();
        vistaModificarNoConsumible vistaModiNo = new vistaModificarNoConsumible();
        if(jRBConsumible.isSelected()){
            ModificarConsumibleControlador modi = new ModificarConsumibleControlador(vistaModi);
            String cveMatCon = modi.extraerCveMatCon(this);
            
            vistaModi.setVisible(true);
            modi.cargarSeleccionadoCon(cveMatCon);
            
        } else {
            if(jRBNoConsumible.isSelected()){
                ModificarNoConsumibleControlador modiNo = new ModificarNoConsumibleControlador(vistaModiNo);
                String idUTNG = modiNo.extraeridUTNG(this);
                
                vistaModiNo.setVisible(true);
                modiNo.cargarSeleccionadoNoCon(idUTNG);
            }
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarConsumibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConsumibleActionPerformed
        // TODO add your handling code here:
        vistaAltaHerramientaConsumible altaC = new vistaAltaHerramientaConsumible();
        
        altaC.setVisible(true);
    }//GEN-LAST:event_btnAgregarConsumibleActionPerformed

    private void btnImprimirHerramientas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirHerramientas1ActionPerformed
        // TODO add your handling code here:
        if((jRBConsumible.isSelected() != true) || (jRBNoConsumible.isSelected()) != true ){
            controlador.exportarTablaAExcel(tblMaterial);
        }else{
            JOptionPane.showMessageDialog(null,"Selecciona el tipo de material que se mostrara en la tabla "
                + "y carga todo el material de la tabla para que se pueda exportar toda la informacion en el Excel");
            
        }
    }//GEN-LAST:event_btnImprimirHerramientas1ActionPerformed

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JMenuItem getjMICerrarSesion() {
        return jMICerrarSesion;
    }

    public JTable getTblMaterial() {
        return tblMaterial;
    }

    public JTextField getTxtNoControl() {
        return txtNoControl;
    }

    public JPanel getjPFondo() {
        return jPFondo;
    }

    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public ButtonGroup getTipMat() {
        return tipMat;
    }

    public ButtonGroup getTipId() {
        return tipId;
    }

    public JRadioButton getjRBConsumible() {
        return jRBConsumible;
    }

    public JRadioButton getjRBNoConsumible() {
        return jRBNoConsumible;
    }

    public JRadioButton getjRBEstatal() {
        return jRBEstatal;
    }

    public JRadioButton getjRBLocal() {
        return jRBLocal;
    }

    public JRadioButton getjRBUTNG() {
        return jRBUTNG;
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }
    
    public JButton getBtnAgregar() {
        return btnAgregarNoConsumible;
    }
    
    public JButton getBtnEliminar() {
        return btnEliminar;
    }
    
    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JRadioButton getjRBCveMatCon() {
        return jRBCveMatCon;
    }
    
    public boolean isConsumibleSelected(){
        return jRBConsumible.isSelected();
    }
    
    public boolean isNoConsumibleSelected(){
        return jRBNoConsumible.isSelected();
    }
    
    public String getClaveSeleccionada(){
        int filaSeleccionada = tblMaterial.getSelectedRow();
        if(filaSeleccionada == -1) {
            return null;
        }
        return (String) tblMaterial.getValueAt(filaSeleccionada, 0);
    }
      
    public void mostrarConfirmacionEliminar(Runnable onConfirm){
        int respuesta = JOptionPane.showConfirmDialog(
        this, "¿Está seguro que desea eliminar este registro?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION);
        
        if(respuesta == JOptionPane.YES_NO_OPTION){
            onConfirm.run();
        }
    }
    
    public void mostrarMensaje(String mensaje){
        JOptionPane.showMessageDialog(
        this,
        mensaje,
        "Sistema",
        JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaListaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaListaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaListaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaListaMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarConsumible;
    private javax.swing.JButton btnAgregarNoConsumible;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimirHerramientas1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenuBar jMBar;
    private javax.swing.JMenuItem jMICerrarSesion;
    private javax.swing.JMenu jMOpciones;
    private javax.swing.JPanel jPDatos;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JPanel jPTablaMaterial;
    private javax.swing.JRadioButton jRBConsumible;
    private javax.swing.JRadioButton jRBCveMatCon;
    private javax.swing.JRadioButton jRBEstatal;
    private javax.swing.JRadioButton jRBLocal;
    private javax.swing.JRadioButton jRBNoConsumible;
    private javax.swing.JRadioButton jRBUTNG;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNoControl;
    private javax.swing.JTable tblMaterial;
    private javax.swing.ButtonGroup tipId;
    private javax.swing.ButtonGroup tipMat;
    private javax.swing.JTextField txtNoControl;
    // End of variables declaration//GEN-END:variables
}