/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.prestamo;

import controlador.ControladorVistaListaPrestamos;
import controlador.DevolucionPrestamoControlador;
import controlador.DuplicarPrestamoControlador;
import controlador.EliminarPrestamoControlador;
import controlador.ModificarPrestamosControlador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mr.Robot
 */
public class VistaListaPrestamos extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla = null;  
    private ControladorVistaListaPrestamos controlador = null;

    /**
     * Creates new form VistaListaPrestamos
     */
    public VistaListaPrestamos() {
        initComponents();
        
        modeloTabla = new DefaultTableModel();
        tblPrestamos.setModel(modeloTabla);
        
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("No. docente");
        modeloTabla.addColumn("No. alumno");
        modeloTabla.addColumn("ID administrador");
        modeloTabla.addColumn("Grupo");
        modeloTabla.addColumn("Materia");
        modeloTabla.addColumn("Observaciones");
        modeloTabla.addColumn("Salida");
        modeloTabla.addColumn("Entrada");
        
        controlador = new ControladorVistaListaPrestamos(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero = new javax.swing.ButtonGroup();
        jPFondo = new javax.swing.JPanel();
        jPDatos = new util.fondo.TransparentPanel();
        jPTablaPrestamos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnRegresado = new javax.swing.JButton();
        btnDuplicar = new javax.swing.JButton();
        lblNoControl = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jRBNoVale = new javax.swing.JRadioButton();
        jRBNoControl = new javax.swing.JRadioButton();
        jRBNoTrabajador = new javax.swing.JRadioButton();
        btnCargar = new javax.swing.JButton();
        jMBar = new javax.swing.JMenuBar();
        jMOpciones = new javax.swing.JMenu();
        jMICerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Prestamos");
        setResizable(false);

        jPDatos.setOpaque(false);

        jPTablaPrestamos.setOpaque(false);

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrestamos);

        btnEliminar.setBackground(new java.awt.Color(40, 167, 69));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar prestamo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(40, 167, 69));
        btnModificar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnModificar.setText("Modificar prestamo");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnRegresado.setBackground(new java.awt.Color(40, 167, 69));
        btnRegresado.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnRegresado.setText("Devolución");
        btnRegresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresadoActionPerformed(evt);
            }
        });

        btnDuplicar.setBackground(new java.awt.Color(40, 167, 69));
        btnDuplicar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnDuplicar.setText("Duplicar prestamo");
        btnDuplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTablaPrestamosLayout = new javax.swing.GroupLayout(jPTablaPrestamos);
        jPTablaPrestamos.setLayout(jPTablaPrestamosLayout);
        jPTablaPrestamosLayout.setHorizontalGroup(
            jPTablaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
            .addGroup(jPTablaPrestamosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnModificar)
                .addGap(47, 47, 47)
                .addComponent(btnDuplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(42, 42, 42)
                .addComponent(btnRegresado)
                .addGap(25, 25, 25))
        );
        jPTablaPrestamosLayout.setVerticalGroup(
            jPTablaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTablaPrestamosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPTablaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnRegresado)
                    .addComponent(btnDuplicar)
                    .addComponent(btnModificar))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        lblNoControl.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblNoControl.setText("Buscar:");

        txtNo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(40, 167, 69));
        btnBuscar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBuscar.setText("Buscar");

        btnVolver.setBackground(java.awt.Color.gray);
        btnVolver.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnVolver.setText("Volver");

        numero.add(jRBNoVale);
        jRBNoVale.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRBNoVale.setText("No. Vale");

        numero.add(jRBNoControl);
        jRBNoControl.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRBNoControl.setText("No.Control");

        numero.add(jRBNoTrabajador);
        jRBNoTrabajador.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRBNoTrabajador.setText("No.Trabajador Docente");

        btnCargar.setBackground(new java.awt.Color(40, 167, 69));
        btnCargar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnCargar.setText("Cargar");

        javax.swing.GroupLayout jPDatosLayout = new javax.swing.GroupLayout(jPDatos);
        jPDatos.setLayout(jPDatosLayout);
        jPDatosLayout.setHorizontalGroup(
            jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosLayout.createSequentialGroup()
                        .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPDatosLayout.createSequentialGroup()
                                .addComponent(lblNoControl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCargar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVolver))
                            .addComponent(jPTablaPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(jPDatosLayout.createSequentialGroup()
                        .addComponent(jRBNoVale, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRBNoControl)
                        .addGap(27, 27, 27)
                        .addComponent(jRBNoTrabajador)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPDatosLayout.setVerticalGroup(
            jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoControl)
                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnVolver)
                    .addComponent(btnCargar))
                .addGap(18, 18, 18)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBNoVale)
                    .addComponent(jRBNoControl)
                    .addComponent(jRBNoTrabajador))
                .addGap(16, 16, 16)
                .addComponent(jPTablaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jMOpciones.setText("Opciones");

        jMICerrarSesion.setText("Cerrar sesión");
        jMOpciones.add(jMICerrarSesion);

        jMBar.add(jMOpciones);

        setJMenuBar(jMBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        EliminarPrestamoControlador elicont = new EliminarPrestamoControlador(this);
        
        try {
            elicont.eliminarPrestamo();
        } catch (SQLException ex) {
            Logger.getLogger(VistaListaPrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            // TODO add your handling code here:
            VistaModificarPrestamo vista = new VistaModificarPrestamo();
            
            
            ModificarPrestamosControlador modiPre = new ModificarPrestamosControlador(vista);
            int cvePre = modiPre.extraerCvePre(this);
            
            if(cvePre > 0){
                ModificarPrestamosControlador controladorModificar = new ModificarPrestamosControlador(vista);
                vista.setVisible(true);
                controladorModificar.cargarTodosDatos(cvePre);
                //controladorModificar.cargarListaPreCon(cvePre);
                //controladorModificar.cargarListaPreNoCon(cvePre);
                
                this.setVisible(false);
                
            }else {
                JOptionPane.showMessageDialog(this, "Escoja el prestamo a modificar");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VistaListaPrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresadoActionPerformed
        // TODO add your handling code here:
        DevolucionPrestamoControlador devo = new DevolucionPrestamoControlador(this);
        int cvePre = devo.extraerCvePre(this);
        
        if(cvePre > 0){
                
            String hora = devo.extraerFecha();
            try {
                devo.regresarPrestamo(cvePre, hora);
                JOptionPane.showMessageDialog(this, "Prestamo devuelto correctamente");
                ControladorVistaListaPrestamos contPre = new ControladorVistaListaPrestamos(this);
                
                DefaultTableModel modelo = (DefaultTableModel) tblPrestamos.getModel();
                modelo.setRowCount(0);
                contPre.cargarPrestamos();
            } catch (SQLException ex) {
                Logger.getLogger(VistaListaPrestamos.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }else {
            JOptionPane.showMessageDialog(this, "Escoja el prestamo a devolver");
        }
    }//GEN-LAST:event_btnRegresadoActionPerformed

    private void btnDuplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuplicarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            VistaDuplicarPrestamo vista = new VistaDuplicarPrestamo();
           
            DuplicarPrestamoControlador modiPre = new DuplicarPrestamoControlador(vista);
            int cvePre = modiPre.extraerCvePre(this);
            
            if(cvePre > 0){
                DuplicarPrestamoControlador controladorDuplicar = new DuplicarPrestamoControlador(vista);
                vista.setVisible(true);
                vista.cargarDocentes();
                vista.cargarAdmin();
                controladorDuplicar.cargarTodosDatos(cvePre);
                
                //controladorModificar.cargarListaPreCon(cvePre);
                //controladorModificar.cargarListaPreNoCon(cvePre);
                
                this.setVisible(false);
                
            }else {
                JOptionPane.showMessageDialog(this, "Escoja el prestamo a duplicar");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VistaListaPrestamos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDuplicarActionPerformed

    public JPanel getjPFondo() {
        return jPFondo;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JTable getTblPrestamos() {
        return tblPrestamos;
    }

    public JTextField getTxtNo() {
        return txtNo;
    }

    public JMenuItem getjMICerrarSesion() {
        return jMICerrarSesion;
    }

    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public JRadioButton getjRBNoVale(){
        return jRBNoVale;
    }
    
    public JRadioButton getjRBNoControl() {
        return jRBNoControl;
    }

    public JRadioButton getjRBNoTrabajador() {
        return jRBNoTrabajador;
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public JButton getBtnCargar() {
        return btnCargar;
    }
                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaListaPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaListaPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaListaPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaListaPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnDuplicar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresado;
    private javax.swing.JButton btnVolver;
    private javax.swing.JMenuBar jMBar;
    private javax.swing.JMenuItem jMICerrarSesion;
    private javax.swing.JMenu jMOpciones;
    private javax.swing.JPanel jPDatos;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JPanel jPTablaPrestamos;
    private javax.swing.JRadioButton jRBNoControl;
    private javax.swing.JRadioButton jRBNoTrabajador;
    private javax.swing.JRadioButton jRBNoVale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNoControl;
    private javax.swing.ButtonGroup numero;
    private javax.swing.JTable tblPrestamos;
    private javax.swing.JTextField txtNo;
    // End of variables declaration//GEN-END:variables
}
