/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.administrador;

import controlador.ControladorVistaListaAdministradores;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mr.Robot
 */
public class VistaListaAdministradores extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla = null;
    private ControladorVistaListaAdministradores controlador = null;
    

    /**
     * Creates new form VistaListaPrestamos
     */
    public VistaListaAdministradores() {
        initComponents();
        
        modeloTabla = new DefaultTableModel();
        tblAdministradores.setModel(modeloTabla);
        
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido Paterno");
        modeloTabla.addColumn("Apellido Materno");
        modeloTabla.addColumn("No. Trabajador");
        modeloTabla.addColumn("Correo");
        modeloTabla.addColumn("Contraseña");
              
        controlador = new ControladorVistaListaAdministradores(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.ButtonGroup();
        jPFondo = new javax.swing.JPanel();
        jPDatos = new util.fondo.PanelTransparente();
        jPTablaPrestamos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdministradores = new javax.swing.JTable();
        lblNoControl = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jRBNoTrabajadorAdministrador = new javax.swing.JRadioButton();
        btnVolver = new javax.swing.JButton();
        jRBId = new javax.swing.JRadioButton();
        btnCargar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jMBar = new javax.swing.JMenuBar();
        jMOpciones = new javax.swing.JMenu();
        jMICerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administradores");
        setPreferredSize(new java.awt.Dimension(960, 700));
        setResizable(false);

        jPTablaPrestamos.setOpaque(false);

        tblAdministradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAdministradores);

        javax.swing.GroupLayout jPTablaPrestamosLayout = new javax.swing.GroupLayout(jPTablaPrestamos);
        jPTablaPrestamos.setLayout(jPTablaPrestamosLayout);
        jPTablaPrestamosLayout.setHorizontalGroup(
            jPTablaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPTablaPrestamosLayout.setVerticalGroup(
            jPTablaPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTablaPrestamosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 191, Short.MAX_VALUE))
        );

        lblNoControl.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblNoControl.setText("Buscar:");

        txtId.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(40, 167, 69));
        btnBuscar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBuscar.setText("Buscar");

        id.add(jRBNoTrabajadorAdministrador);
        jRBNoTrabajadorAdministrador.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRBNoTrabajadorAdministrador.setText("No.Trabajador Administrador");

        btnVolver.setBackground(java.awt.Color.gray);
        btnVolver.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnVolver.setText("Volver");

        id.add(jRBId);
        jRBId.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jRBId.setText("ID");

        btnCargar.setBackground(new java.awt.Color(40, 167, 69));
        btnCargar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnCargar.setText("Cargar");

        btnAgregar.setBackground(new java.awt.Color(40, 167, 69));
        btnAgregar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnAgregar.setText("Agregar");

        btnEditar.setBackground(new java.awt.Color(40, 167, 69));
        btnEditar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEditar.setText("Editar");

        btnEliminar.setBackground(java.awt.Color.gray);
        btnEliminar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPDatosLayout = new javax.swing.GroupLayout(jPDatos);
        jPDatos.setLayout(jPDatosLayout);
        jPDatosLayout.setHorizontalGroup(
            jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDatosLayout.createSequentialGroup()
                        .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDatosLayout.createSequentialGroup()
                                .addComponent(lblNoControl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPDatosLayout.createSequentialGroup()
                                .addComponent(jRBId)
                                .addGap(18, 18, 18)
                                .addComponent(jRBNoTrabajadorAdministrador)))
                        .addGap(18, 18, 18)
                        .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPDatosLayout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar))
                            .addGroup(jPDatosLayout.createSequentialGroup()
                                .addComponent(btnCargar)
                                .addGap(54, 54, 54)
                                .addComponent(btnVolver)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jPTablaPrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPDatosLayout.setVerticalGroup(
            jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoControl)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnVolver)
                    .addComponent(btnCargar))
                .addGap(18, 18, 18)
                .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRBNoTrabajadorAdministrador)
                        .addComponent(jRBId))
                    .addGroup(jPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregar)
                        .addComponent(btnEditar)
                        .addComponent(btnEliminar)))
                .addGap(21, 21, 21)
                .addComponent(jPTablaPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPFondoLayout = new javax.swing.GroupLayout(jPFondo);
        jPFondo.setLayout(jPFondoLayout);
        jPFondoLayout.setHorizontalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPFondoLayout.setVerticalGroup(
            jPFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jMOpciones.setText("Opciones");

        jMICerrarSesion.setText("Cerrar sesión");
        jMOpciones.add(jMICerrarSesion);

        jMBar.add(jMOpciones);

        setJMenuBar(jMBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getjPFondo() {
        return jPFondo;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JTable getTblAdministradores() {
        return tblAdministradores;
    }

    public JMenuItem getjMICerrarSesion() {
        return jMICerrarSesion;
    }

    public DefaultTableModel getModeloTabla() {
        return modeloTabla;
    }

    public JButton getBtnVolver() {
        return btnVolver;
    }

    public JButton getBtnCargar() {
        return btnCargar;
    }

    public JRadioButton getjRBId() {
        return jRBId;
    }

    public JRadioButton getjRBNoTrabajadorAdministrador() {
        return jRBNoTrabajadorAdministrador;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }
                         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaListaAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaListaAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaListaAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaListaAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaListaAdministradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup id;
    private javax.swing.JMenuBar jMBar;
    private javax.swing.JMenuItem jMICerrarSesion;
    private javax.swing.JMenu jMOpciones;
    private javax.swing.JPanel jPDatos;
    private javax.swing.JPanel jPFondo;
    private javax.swing.JPanel jPTablaPrestamos;
    private javax.swing.JRadioButton jRBId;
    private javax.swing.JRadioButton jRBNoTrabajadorAdministrador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNoControl;
    private javax.swing.JTable tblAdministradores;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
